apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aws-demo
  region: us-east-1
  version: "1.21"

availabilityZones: ["${AZS[0]}", "${AZS[1]}", "${AZS[2]}"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 2
  instanceType: t3.small

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

# secretsEncryption:
#   keyARN: ${MASTER_ARN}